version: '3.7'
services:
  mysqldb:
    image: mysql:5.7.25
    container_name: mysql
    restart: always
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    volumes:
      - ./schemas:/var/lib/mysql:rw
  # express:
  #   depends_on:
  #     - mysqldb
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: express
  #   restart: always
  #   env_file: ./.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   environment:
  #     - DB_HOST=$DB_NAME
  #     - DB_USER=$MYSQLDB_USER
  #     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #     - DB_NAME=$MYSQLDB_DATABASE
  #     # - DB_PORT=$MYSQLDB_DOCKER_PORT
  #   links:
  #     - mysqldb:mysqldb
volumes:
  schemas: {}

